#!/bin/bash
echo "=== Robot Dog Servo Power Diagnostic ==="
echo ""
echo "Check these connections on the robot:"
echo ""
echo "1. EXTERNAL POWER SUPPLY for servos:"
echo "   - Should be 5V-6V, 5A+ (for 12 servos)"
echo "   - VCC connected to servo RED wires"
echo "   - GND connected to servo BLACK/BROWN wires"
echo ""
echo "2. PCA9685 CONNECTIONS:"
echo "   - VCC pin: Connect to 5V (from Pi or external)"
echo "   - GND pin: Connect to GND (MUST be common with servo GND)"
echo "   - SDA: Connect to Pi I2C-0 SDA"
echo "   - SCL: Connect to Pi I2C-0 SCL"
echo ""
echo "3. SERVO SIGNAL WIRES:"
echo "   - Channel 0-11 outputs connect to servo ORANGE/YELLOW wires"
echo "   - Verify continuity with multimeter"
echo ""
echo "4. GROUND CONNECTIONS (CRITICAL):"
echo "   - Pi GND <--> PCA9685 GND <--> External Power GND <--> Servo GND"
echo "   - All grounds MUST be connected together!"
echo ""
echo "Quick test with multimeter:"
echo "  - Measure voltage on servo RED wire: should be 5V-6V"
echo "  - Measure voltage on PCA9685 VCC pin: should be 5V"
echo "  - Check continuity: all GND pins should be connected"
